### ISSUE TITLE
Using on Versa 4

### ISSUE THREAD

**Issue by MarkTheUnruly** [c99koder/fitbit-librelinkup#1]
Hi, I'm a programmer, but mainly VBA these days.

Trying to get this working on a Versa 4, but I can't access developer bridge on Watch or Phone.

Any suugestions?

Mark

**Comment by c99koder** [comment]
The developer bridge is cloud-based, so check your Internet and firewall settings or contact Fitbit developer support https://community.fitbit.com/t5/SDK-Development/bd-p/sdk

Edit: Versa 4 doesn't support 3rd party apps. There is no SDK for Versa 4 or Sense 2.
